### PR TITLE
Remove files and code relating to local database

### PR DESCRIPTION
**Pull request by louisebolden**
Currently, there is no requirement for a local database for this API, as it should only make requests to other APIs and return the gathered responses.

If in future a local database and entities are needed, this PR may be reverted.

### CODE REVIEW

**Review by elcorbs — APPROVED** [review]
Looks good - What are the `.keep` files for?

**Review by Renny4Real — APPROVED** [review]
Looks good. 👍 
Some of these look like formatting changes. We could probably separate these changes from the DB removal changes and have two commits?
If we needed to revert DB removal changes, was wondering if reverting a commit in master would work rather than reverting a PR.

**Comment by louisebolden** [comment]
> Looks good - What are the `.keep` files for?

Just had to double-check in case my knowledge was out of date... [Looks like](https://git.wiki.kernel.org/index.php/GitFaq#Can_I_add_empty_directories.3F) `.keep` files are (still) necessary to retain empty directories in a git repository.

Happy to be corrected if both me _and_ that link are out of date, though!

**Comment by louisebolden** [comment]
> Some of these look like formatting changes. We could probably separate these changes from the DB removal changes and have two commits?

Oh, that's such a good point. Let me separate out the formatting changes.

> If we needed to revert DB removal changes, was wondering if reverting a commit in master would work rather than reverting a PR.

If we had the formatting changes in a separate commit here, you mean? I'm not sure - will remove them from here and either PR them separately or... leave it for later. 😅

**Comment by elcorbs** [comment]
> > Looks good - What are the `.keep` files for?
> 
> Just had to double-check in case my knowledge was out of date... [Looks like](https://git.wiki.kernel.org/index.php/GitFaq#Can_I_add_empty_directories.3F) `.keep` files are (still) necessary to retain empty directories in a git repository.
> 
> Happy to be corrected if both me _and_ that link are out of date, though!

That makes sense, I've just not seen them before.

**Pull request merged**
