### PR TITLE
An initial E2E test, just to confirm a 200 response is returned.

### PR DESCRIPTION
**Pull request by elcorbs**
configure services
setup wiremock to mock API responses in integration tests
add paths to API requests
changes API requests to be get GET requests

In a later PR will check that actual data for the API's is also being returned.

### CODE REVIEW

**Review by LBHBomotoso — APPROVED** [review]
looks fine

**Review by humulla — APPROVED** [review]
Looks good to me!

**Review by louisebolden — APPROVED** [review]
Really good starter E2E test with mock servers example 🎉

**Review by Renny4Real — APPROVED** [review]
Looks great. 🎉

**Pull request merged**
